### ISSUE TITLE
Create package in pub.dev

### ISSUE THREAD

**Issue by ShookLyngs** [tekartik/app_camera.dart#13]
Is it possible that we create a package in pub.dev, so users can add it as a dependency, but easier?

**Comment by alextekartik** [comment]
It contains a bunch of git dependencies and it is always a tough decision to decide to publish it and maintain it forever. So the plan is not to publish it on pub for now. However I do maintain git packages. You are welcome to use it as a base for a package and I'll happy to contribute.
