### ISSUE TITLE
Not asking for camera permission 

### ISSUE THREAD

**Issue by vbakale** [tekartik/app_camera.dart#4]
implemented as show maybe i have went somewhere wrong. it is not asking for camera permission and hence unable to open camera for scanning. is there any document for the same?

**Comment by alextekartik** [comment]
Permission is not something we have control on. Each browwer can implement it the way it wants. Typically it will prompt for accessing the camera when you try to use it (getUserMedia).

You should try the smallest example here first: https://github.com/tekartik/app_camera.dart/tree/master/camera_web/example/raw

As a note, it only works on https (not http). http is only accepted on localhost (so useful during development). You can also look at the console as it should give you the relevant warning.
